### PR TITLE
[DONE] Anh/review scanner

### PR DESCRIPTION
**Pull request by anhnguyen6535**

### CODE REVIEW

**Review by jesscsang — CHANGES_REQUESTED** [review]
Three things:
1) the code you added to the SystemControl for the override barcodeScanned method should actually go in ItemControl.
2) The inventory code you added to FakeDataInitializer should be moved into either a separate class or a static method to be initialize in the App.java as the FakeDataInitializer is called every time a station is set up. So the inventory is in essence stocked the number of times we create tabs for stations.
3) I am not sure if the Test Suit was working correctly before you made changes but one of the test cases failed `testPlaceItemWrongItem`

**Comment by anhnguyen6535** [comment]
1. The reason why I put it in StationControl is to prevent the expected weight and other steps in StationControl.barcodeScanned being executed if scan failed. 
3. That test failed in Main from which I pulled. I plan to look at these tests later on.

**Review by jesscsang — APPROVED** [review]

**Review by RowanDavitt — COMMENTED** [review]
Looks good, everything seems to run correctly. 

A few small things I noticed

In check inventory the out of stock line is only printed when the stock for the product is already 0 when the functions called. You might want to change this to run when the stock first becomes 0 as well.

There's also a comment in check inventory that mentions informing the customer about an item being out of stock. At this point the customer would already has the item so it being out of stock doesn't affect them. 
In this case the inventory saying an item is out stock doesn't mean the item the customer has is invalid, It would just mean the inventory wasn't properly recorded (which is stated as a possibility in the comments for inventory in productDatabases)

**Review by RowanDavitt — APPROVED** [review]
Looks good, everything seems to run correctly. 

A few small things I noticed

In check inventory the out of stock line is only printed when the stock for the product is already 0 when the functions called. You might want to change this to run when the stock first becomes 0 as well.

There's also a comment in check inventory that mentions informing the customer about an item being out of stock. At this point the customer would already has the item so it being out of stock doesn't affect them. 
In this case the inventory saying an item is out stock doesn't mean the item the customer has is invalid, It would just mean the inventory wasn't properly recorded (which is stated as a possibility in the comments for inventory in productDatabases)

**Review by hackrmomo — APPROVED** [review]

**Pull request merged**
