### PR TITLE
[DONE] Functionality of Permit Station Use

### PR DESCRIPTION
**Pull request by JonathanYonghoonCho**
edited AttendantControl and AttendantControlListener and created test in AttendantControl for implemented methods

### CODE REVIEW

**Review by liza-khr — DISMISSED** [review]
Looks good to me

**Review by RowanDavitt — CHANGES_REQUESTED** [review]
It looks pretty good, but it looks like you might have forgotten to put a break; in the permit_use case of the perform action switch in attendantControl (line 220). 

As a result whenever permit_use is called, prevent_use is also called. This seems to break your test case.

**Review by JonathanYonghoonCho — COMMENTED** [review]
changes made

**Review by RowanDavitt — APPROVED** [review]
looks good, everything seems to work.

**Review by anhnguyen6535 — APPROVED** [review]

**Pull request merged**
